# Generated by Django 3.2 on 2022-04-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
